// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spb-t4nd6bt21y786pg9.supabase.opentrust.net";
const SUPABASE_PUBLISHABLE_KEY = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiYW5vbiIsInJlZiI6InNwYi10NG5kNmJ0MjF5Nzg2cGc5IiwiaXNzIjoic3VwYWJhc2UiLCJpYXQiOjE3NzY3OTI1MzQsImV4cCI6MjA5MjM2ODUzNH0.fcqkegc-J79crhDIsoifNk0Xp0aY77wOm6cM2unE1QU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
